import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AuthProvider from "@/lib/next-auth-provider";
import { ReactQueryClientProvider } from "@/lib/react-query-provider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/next-auth-provider/auth-options";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
const session = await getServerSession(authOptions);
  return (
    <html lang="en">
<>
<AuthProvider session={session}>
    <ReactQueryClientProvider>
         <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children} <Toaster />
        </body>
    </ReactQueryClientProvider>
</AuthProvider>
</>
    </html>
  );
}
